spring.application.name=mascotas

spring.datasource.url=jdbc:postgresql://dpg-d6se8avgi27c73d2rcs0-a.oregon-postgres.render.com:5432/mascotas_db_rsih
spring.datasource.username=mascotas_db_rsih_user
spring.datasource.password=TlYVEJclCBxiDFfbyFXg0Ru6CR6fjAir

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}